version: '3'
services:
  python:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 'genshin-Artifacter'
    working_dir: '/genshin-Artifacter'
    tty: true
    volumes:
      - ./:/genshin-Artifacter
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - '192.168.1.28:50021:50021'
    restart: unless-stopped